Repository hmcts/pcq-loader, pull requests merged in 2020-07, with the labels that each got.

#2 PCQ_588_Removed IDAM dependenccy
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-2

#3 PCQ_588_Fixed Spring Boot Error
  build.gradle
  charts/pcq-loader/Chart.yaml
  charts/pcq-loader/requirements.yaml
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-3

#4 PCQ_588_Cosmetic change to trigger build
  src/main/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderApplication.java
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-4

#5 Pcq 588 blob storage configuration
  infrastructure/storage-account-staging.tf
  infrastructure/storage-account.tf
  infrastructure/variables.tf
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-5

#6 PCQ-588: Update to add containers.
  Jenkinsfile_CNP
  infrastructure/storage-account.tf
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-6

#7 Update storage-account.tf
  infrastructure/storage-account.tf
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-7
