Repository hmcts/pcq-loader, pull requests merged in 2020-12, with the labels that each got.

#56 PCQ-740: Update to fix dependancy vulnerability.
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-56

#57 PCQ-742 Addressing CVE-2020-17527 in PCQ-Loader
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-57

#58 PCQ_744 - Added suppression for low severity unused CVE
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-58
