Repository hmcts/pcq-loader, pull requests merged in 2020-08, with the labels that each got.

#8 PCQ-588: Updated to add missing variables.
  infrastructure/storage-account.tf
  infrastructure/variables.tf
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-8

#9 Pcq 588 blob storage container
  infrastructure/storage-account.tf
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-9

#10 Pcq 588 blob storage container
  infrastructure/storage-account.tf
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-10

#11 Pcq 588 blob storage container
  infrastructure/storage-account.tf
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-11

#12 PCQ-588: Correction to container config.
  infrastructure/storage-account.tf
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-12

#13 Pcq 588 blob storage container
  Jenkinsfile_CNP
  infrastructure/storage-account.tf
  infrastructure/variables.tf
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-13

#14 PCQ-588 Remove container creation as this was done through UI.
  infrastructure/storage-account.tf
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-14

#16 PCQ-588 fixing build.
  infrastructure/outputs.tf
  infrastructure/state.tf
  infrastructure/storage-account.tf
  infrastructure/variables.tf
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-16

#15 PCQ-577_DCN_Number_Extraction
  .travis.yml
  Dockerfile
  src/main/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderApplication.java
  src/main/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderComponent.java
  src/main/java/uk/gov/hmcts/reform/pcqloader/utils/PcqLoaderUtils.java
  src/test/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderApplicationTest.java
  src/test/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderComponentTest.java
  src/test/java/uk/gov/hmcts/reform/pcqloader/utils/PcqLoaderUtilsTest.java
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-15

#17 PCQ-572: Update to add pcq container.
  .gitignore
  infrastructure/storage-account.tf
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-17

#18 PCQ-572: Update to add pcq container.
  infrastructure/providers.tf
  infrastructure/storage-account.tf
  infrastructure/variables.tf
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-18

#19 Pcq 572 blob storage authentication
  infrastructure/providers.tf
  infrastructure/storage-account.tf
  infrastructure/variables.tf
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-19

#20 Pcq 572 blob storage authentication
  Jenkinsfile_CNP
  build.gradle
  charts/pcq-loader/Chart.yaml
  charts/pcq-loader/values.yaml
  infrastructure/providers.tf
  infrastructure/storage-account-staging.tf
  infrastructure/storage-account.tf
  infrastructure/variables.tf
  src/functionalTest/java/uk/gov/hmcts/reform/pcqloader/config/TestApplicationConfiguration.java
  src/functionalTest/java/uk/gov/hmcts/reform/pcqloader/postdeploy/PcqLoaderFunctionalTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/pcqloader/postdeploy/PcqLoaderTestBase.java
  src/functionalTest/resources/application-functional.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/pcqloader/config/TestApplicationConfiguration.java
  src/integrationTest/java/uk/gov/hmcts/reform/pcqloader/services/BlobStorageManagerTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/pcqloader/util/SpringBootIntegrationTest.java
  src/integrationTest/resources/application.properties
  src/integrationTest/resources/docker-compose.yml
  src/integrationTest/resources/test/azurite/read.me
  src/integrationTest/resources/testcontainers.properties
  src/main/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderApplication.java
  src/main/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderComponent.java
  src/main/java/uk/gov/hmcts/reform/pcqloader/config/BlobStorageConfiguration.java
  src/main/java/uk/gov/hmcts/reform/pcqloader/config/BlobStorageProperties.java
  src/main/java/uk/gov/hmcts/reform/pcqloader/services/BlobStorageManager.java
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yaml
  src/test/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderApplicationTest.java
  src/test/java/uk/gov/hmcts/reform/pcqloader/PcqLoaderComponentTest.java
  src/test/java/uk/gov/hmcts/reform/pcqloader/config/BlobStorageConfigurationTest.java
  src/test/java/uk/gov/hmcts/reform/pcqloader/services/BlobStorageManagerTest.java
  src/test/resources/application.yaml
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-20
