Repository hmcts/pcq-loader, pull requests merged in 2021-07, with the labels that each got.

#78 Nightly dev
  security.sh
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-78

#79 PCQ-873: Updated to capture any error during metafile parsing.
  src/.DS_Store
  src/functionalTest/java/uk/gov/hmcts/reform/pcqloader/postdeploy/PcqLoaderFunctionalTest.java
  src/functionalTest/resources/BlobTestFiles/1579002496_01-07-2021-16-45-00.zip
  src/main/java/uk/gov/hmcts/reform/pcqloader/helper/PayloadMappingHelper.java
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-79

#80 PCQ-885: UpdatedPcqCommonsLocation
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-80

#81 fix for CVE-2021-33037
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-81

#82 PCQ-880: Updated to add fortify pipeline
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-82
