Repository hmcts/pcq-loader, pull requests merged in 2021-12, with the labels that each got.

#100 PCQ-1190 Diable Loader Fortify Scan
  Jenkinsfile_nightly
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-100

#101 PCQ-1195 log4j upgrade
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-101

#103 PCQ-1212 Enable Fortify Scan
  Jenkinsfile_nightly
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-103

#102 PCQ‐1134: Update pcq-loader to Gradle 7.2
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-102
