Repository hmcts/pcq-loader, pull requests merged in 2022-05, with the labels that each got.

#120 PCQ-1421-remove-redundant-vulnerability-suppressions
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-120

#122 PCQ-1333 spring upgrade
  Jenkinsfile_nightly
  audit.json
  build.gradle
  security.sh
  src/main/java/uk/gov/hmcts/reform/pcqloader/config/SwaggerConfiguration.java
  src/test/java/uk/gov/hmcts/reform/pcqloader/services/impl/PcqBackendServiceImplTest.java
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-122

#123 PCQ-1333Loader other upgrade
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-123

#124 PCQ-87 Dependency check fixed
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-124

#125 PCQ-699 dependency check fix
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-125
