Repository hmcts/pcq-loader, pull requests merged in 2022-04, with the labels that each got.

#116 PCQ-966-dependency-check-spring-beans
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-116

#117 PCQ-1452: Suppress vulnerability with spring-plugin.
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-117

#118 PCQ-1424-Dependency-check-spring-plugin
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-118

#119 PCQ-1423-dependency-check-spring-5.3.18
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-119
