Repository hmcts/pcq-loader, pull requests merged in 2022-02, with the labels that each got.

#104 Pcq 1243
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-104

#105 PCQ-1236 hmcts library upgrade
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-105

#106 PCQ-1338 Dependency Check Fix
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-106

#107 PCQ-986: Spring Security dependency check fix
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-107

#108 Chart Job update
  charts/pcq-loader/Chart.yaml
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-108
