Repository hmcts/pcq-loader, pull requests merged in 2022-11, with the labels that each got.

#178 PCQ-1596 dependency check fix
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-178

#182 PCQ-1593 Add SonarQube badges and Overview section
  README.md
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-182

#184 PCQ-1595 Cleanup helm release on success
  .github/PULL_REQUEST_TEMPLATE.md
  Jenkinsfile_CNP
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-184

#187 PCQ-1600 Upgrading libraries
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-187

#190 Pcq 1600
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-190
