Repository hmcts/pcq-loader, pull requests merged in 2023-11, with the labels that each got.

#397 PCQ-1842 remove dependabot config
  .github/dependabot.yml
Labels: prd:pcq, ns:pcq, rel:pcq-loader-pr-397

#399 PCQ-1750 log 1% of health message in application insight
  lib/applicationinsights.json
Labels: prd:pcq, ns:pcq, rel:pcq-loader-pr-399

#414 PCQ-1847-suppress CVE-2023-36052 until 31-12-2023 and check if fix is…
  config/owasp/suppressions.xml
Labels: prd:pcq, ns:pcq, rel:pcq-loader-pr-414
