Repository hmcts/pcq-loader, pull requests merged in 2023-03, with the labels that each got.

#241 PCQ-1648 Configuring dependabot on particular day
  .github/dependabot.yml
  build.gradle
  charts/pcq-loader/Chart.yaml
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-241

#242 PCQ-1623 removing suppression CVE-2021-67533
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-242

#248 PCQ-1659 suppress CVE-2022-1471
  config/owasp/suppressions.xml
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-248

#254 Fix CVE-2023-28708
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-254

#255 Spring-framework CVE-2023-20861 Fix
  build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-loader-pr-255
